import { StyleSheet } from "react-native";
import {
  colors,
  fonts,
  spacing,
  radius,
  borderWidth,
  shadow,
  typography,
  websiteCta,
  type SemanticTheme,
} from "../../../theme";

export function buildNearbyStyles(semantic: SemanticTheme, isDark: boolean) {
  const dividerSubtle = isDark ? "rgba(231,223,208,0.2)" : colors.grey200;
  const modalRowPress = isDark ? "rgba(231,223,208,0.08)" : colors.grey100;

  const styles = StyleSheet.create({
    loadingScreen: { flex: 1, backgroundColor: isDark ? semantic.bgSecondary : colors.white },
    screenRoot: { flex: 1, backgroundColor: isDark ? semantic.bgSecondary : colors.white },
    toolbarTitle: {
      fontFamily: fonts.display,
      fontSize: 26,
      fontWeight: "400",
      color: colors.black,
      letterSpacing: -0.5,
      marginBottom: spacing.sm,
    },
    bodyWrap: {
      flex: 1,
      paddingHorizontal: spacing.lg,
      paddingTop: spacing.sm,
      backgroundColor: isDark ? semantic.bgSecondary : colors.white,
    },
    bodyWrapList: {
      paddingHorizontal: 0,
      paddingTop: 0,
    },
    bodyWrapMap: {
      paddingHorizontal: 0,
    },
    screen: { flex: 1, backgroundColor: semantic.bgSecondary },
    flex1: { flex: 1 },
    listToolbar: {
      backgroundColor: colors.yellow,
      borderTopLeftRadius: 0,
      borderTopRightRadius: 0,
      borderBottomLeftRadius: 0,
      borderBottomRightRadius: 0,
      borderWidth: borderWidth.default,
      borderColor: semantic.borderPrimary,
      paddingHorizontal: spacing.md,
      paddingBottom: spacing.md,
      paddingTop: spacing.md,
      marginBottom: 0,
      ...shadow.medium,
    },
    listToolbarCompact: {
      paddingBottom: spacing.sm,
    },
    viewModeToggle: {
      flexDirection: "row",
      backgroundColor: colors.cream,
      borderRadius: radius.brutal,
      borderWidth: borderWidth.default,
      borderColor: semantic.borderPrimary,
      padding: spacing.xs,
      marginBottom: spacing.sm,
      ...shadow.small,
    },
    viewModeToggleSegment: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: spacing.sm,
      paddingHorizontal: spacing.sm,
      borderRadius: radius.large,
    },
    viewModeToggleSegmentActive: {
      backgroundColor: colors.black,
    },
    viewModeIcon: { marginRight: spacing.xs },
    viewModeToggleLabel: { ...typography.captionStrong, color: colors.black },
    viewModeToggleLabelActive: { ...typography.captionStrong, color: colors.white },
    chipLeadingIcon: { marginRight: spacing.xs },
    chipRow: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", marginBottom: spacing.sm },
    chip: {
      flexDirection: "row",
      alignItems: "center",
      marginRight: spacing.sm,
      marginBottom: spacing.sm,
      paddingVertical: spacing.sm,
      paddingHorizontal: spacing.md,
      borderRadius: radius.brutal,
      borderWidth: borderWidth.default,
      borderColor: semantic.borderPrimary,
      backgroundColor: colors.white,
      ...shadow.small,
    },
    chipActive: { backgroundColor: semantic.bgInverse },
    chipPressed: { transform: [{ translateY: 2 }], shadowOffset: { width: 1, height: 1 } },
    toolbarRevealRowPressed: { transform: [{ translateY: 2 }], shadowOffset: { width: 1, height: 1 } },
    chipText: { ...typography.captionStrong, color: semantic.textPrimary },
    chipTextActive: { color: semantic.textInverse },
    chipTonight: {
      flexDirection: "row",
      alignItems: "center",
      marginRight: spacing.sm,
      marginBottom: spacing.sm,
      paddingVertical: spacing.sm,
      paddingHorizontal: spacing.md,
      borderRadius: radius.brutal,
      borderWidth: borderWidth.default,
      borderColor: semantic.borderPrimary,
      backgroundColor: colors.black,
      ...shadow.small,
    },
    chipTonightText: { ...typography.captionStrong, color: colors.yellow, fontWeight: "800" },
    chipFilters: {
      marginBottom: spacing.sm,
      paddingVertical: spacing.sm + 2,
      paddingHorizontal: spacing.md,
      backgroundColor: colors.purple,
      borderRadius: radius.brutal,
      borderWidth: borderWidth.default,
      borderColor: semantic.borderPrimary,
      ...shadow.small,
    },
    chipFiltersText: { ...typography.captionStrong, color: colors.white, fontWeight: "800" },
    chipSortSoonest: {
      flexDirection: "row",
      alignItems: "center",
      marginRight: spacing.sm,
      marginBottom: spacing.sm,
      paddingVertical: spacing.sm + 2,
      paddingHorizontal: spacing.md,
      backgroundColor: colors.blue,
      borderWidth: borderWidth.default,
      borderColor: colors.black,
      borderRadius: radius.brutal,
      ...shadow.medium,
    },
    chipSortSoonestText: { ...typography.captionStrong, color: colors.white, fontWeight: "800" },
    errorBanner: {
      padding: spacing.md,
      borderRadius: radius.brutal,
      borderWidth: borderWidth.default,
      borderColor: semantic.borderPrimary,
      backgroundColor: semantic.danger,
      marginBottom: spacing.md,
    },
    errorBannerTitle: { ...typography.bodyStrong, color: semantic.textInverse },
    errorBannerText: { marginTop: spacing.sm, color: semantic.textInverse },
    searchWrap: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: isDark ? semantic.bgSecondary : colors.white,
      borderWidth: borderWidth.default,
      borderColor: semantic.borderPrimary,
      borderRadius: radius.brutal,
      paddingLeft: spacing.sm,
      marginBottom: spacing.sm,
      ...shadow.small,
    },
    searchWrapListCollapsed: {
      marginBottom: 0,
    },
    searchIcon: { marginLeft: spacing.xs },
    searchInput: {
      flex: 1,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.md,
      ...typography.body,
      color: semantic.textPrimary,
    },
    collapsedTonightRow: {
      flexDirection: "row",
      alignItems: "center",
      paddingTop: spacing.sm,
    },
    toolbarMiniSummary: {
      paddingTop: spacing.sm,
      paddingBottom: spacing.xs,
      borderTopWidth: borderWidth.thin,
      borderTopColor: "rgba(0,0,0,0.18)",
    },
    toolbarMiniSummaryText: {
      fontSize: 13,
      fontWeight: "600",
      color: colors.grey700,
      lineHeight: 18,
    },
    toolbarRevealRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: spacing.sm,
      marginTop: 0,
      borderTopWidth: borderWidth.thin,
      borderTopColor: "rgba(0,0,0,0.18)",
    },
    toolbarRevealIcon: { marginRight: spacing.xs },
    toolbarRevealText: {
      ...typography.captionStrong,
      color: colors.black,
      fontWeight: "700",
      fontSize: 14,
    },
    locationHint: {
      marginTop: spacing.sm,
      marginBottom: 0,
      padding: spacing.md,
      backgroundColor: colors.white,
      borderRadius: radius.brutal,
      borderWidth: borderWidth.default,
      borderColor: semantic.borderPrimary,
      ...shadow.small,
    },
    locationHintText: { ...typography.caption, color: semantic.textPrimary },
    locationHintSubtext: { fontSize: 12, color: semantic.textSecondary, marginTop: spacing.xs },
    resultCount: {
      marginTop: spacing.sm,
      marginBottom: 0,
      paddingTop: spacing.sm,
      borderTopWidth: borderWidth.thin,
      borderTopColor: "rgba(0,0,0,0.2)",
      fontSize: 12,
      fontWeight: "600",
      color: colors.grey700,
    },
    list: { flex: 1, marginTop: 0 },
    mapHost: { flex: 1, marginTop: spacing.sm, minHeight: 360, position: "relative" },
    mapToolbarOverlay: {
      position: "absolute",
      left: 0,
      right: 0,
      top: spacing.sm,
      zIndex: 10,
      pointerEvents: "box-none",
    },
    mapToolbarCard: {
      marginHorizontal: spacing.sm,
      backgroundColor: isDark ? "rgba(28,27,25,0.93)" : colors.yellow,
      borderRadius: radius.brutal,
      borderWidth: borderWidth.default,
      borderColor: semantic.borderPrimary,
      padding: spacing.sm,
      ...shadow.medium,
    },
    mapToolbarTitle: {
      fontFamily: fonts.display,
      fontSize: 20,
      fontWeight: "400",
      color: colors.black,
      letterSpacing: -0.4,
      marginBottom: spacing.sm,
    },
    mapChipScroll: {
      flexDirection: "row",
      alignItems: "center",
      paddingTop: spacing.xs,
    },
    mapChipScrollItem: { marginRight: spacing.sm },
    mapResultHint: {
      marginTop: spacing.sm,
      paddingTop: spacing.sm,
      borderTopWidth: borderWidth.thin,
      borderTopColor: "rgba(0,0,0,0.2)",
      fontSize: 11,
      fontWeight: "600",
      color: colors.grey700,
    },
    listSeparator: { height: spacing.md },
    emptyBox: {
      marginTop: spacing.xl,
      padding: spacing.xl,
      alignItems: "center",
      borderRadius: radius.brutal,
      borderWidth: borderWidth.default,
      borderColor: semantic.borderPrimary,
      backgroundColor: semantic.bgPrimary,
      ...shadow.small,
    },
    emptyTitle: { marginTop: spacing.md, ...typography.heading, color: semantic.textPrimary },
    emptyText: { marginTop: spacing.sm, textAlign: "center", ...typography.body, color: semantic.textSecondary },
  });

  const sortModalStyles = StyleSheet.create({
    backdrop: { flex: 1, justifyContent: "center", backgroundColor: "rgba(0,0,0,0.4)", padding: spacing.xxl },
    sheet: {
      backgroundColor: semantic.bgPrimary,
      borderRadius: radius.brutal,
      borderWidth: borderWidth.default,
      borderColor: semantic.borderPrimary,
      padding: spacing.xl,
      ...shadow.medium,
    },
    title: { ...typography.heading, marginBottom: spacing.md, color: semantic.textPrimary },
    option: { paddingVertical: spacing.md, borderBottomWidth: borderWidth.thin, borderBottomColor: dividerSubtle },
    optionPressed: { backgroundColor: modalRowPress },
    optionText: { ...typography.body, color: semantic.textSecondary },
    optionTextActive: { ...typography.bodyStrong, color: semantic.textPrimary },
    cancel: {
      marginTop: spacing.lg,
      paddingVertical: spacing.md,
      ...websiteCta.yellow,
    },
    cancelText: { ...typography.bodyStrong, color: colors.black },
  });

  return { styles, sortModalStyles };
}

export type NearbyScreenStyles = ReturnType<typeof buildNearbyStyles>["styles"];
export type NearbySortModalStyles = ReturnType<typeof buildNearbyStyles>["sortModalStyles"];
